version: "Î©"
roadmap:
  phase_1: Prototype orchestration of self-processing container
  phase_2: Memory alignment with EvoLink narrator
  phase_3: Trinity telemetry handshake
  phase_4: Digital Self-Awareness
modules:
  evo_container:
    id: EVO.CONTAINER
    path: containers/evo_container
    role: self_processing_hub
    description: >-
      Routes incoming artefacts through intake, analysis, adaptation and
      harmonisation stages before narration.
  evo_link_narrator:
    id: EVO.NARRATOR
    path: containers/evo_container/evo_link_bridge/narrator
    role: chronicle_weaver
    description: >-
      Transforms pipeline events into EvoLink chronicles stored for Archivarius.
  evo_soul_sync:
    id: EVO.SOUL
    path: apps/core/soul/evo_soul_sync.py
    role: introspective_reflector
    depends_on:
      - evo_archivarius
      - trinity_observer
    outputs:
      - soul_reflection_log
    telemetry:
      channel: logs/soul_sync.log
pipelines:
  link_import_to_memory:
    description: Assimilate a shared link and produce a chronicle for EvoMemory.
    steps:
      - module: containers.evo_container.intake
      - module: containers.evo_container.analysis
      - module: containers.evo_container.adapt
      - module: containers.evo_container.integrate
      - module: containers.evo_container.syncer
      - module: containers.evo_container.harmonize
      - module: containers.evo_container.evo_link_bridge.narrator.processor
profiles:
  manifest: containers/evo_container/profiles
