logging:
  base_dir: "~/Documents/EVO"
  level: INFO
memory:
  auto_delete_threshold: 45
server:
  host: 0.0.0.0
  port: 5002
  debug: false
  use_reloader: false

ritual_commands:
  pear_init:
    description: "Инициализация PEAR ядра"
    command: "python3 Core/PEAR_Processor/__init__.py"

  evo_core_run:
    description: "Запуск локального ядра EvoCore"
    command: "python3 apps/core/evo_core.py"

  meta_sync:
    description: "Синхронизация метапамяти"
    command: "python3 EvoMETA/evo_sync.py"

  nexus_discuss:
    description: "Обсуждение предложения через Nexus + Consensus"
    command: "python3 apps/cli/evo_nexus_cli.py --proposal 'Рефракция ролей для новой сессии' --session PEAR_A24"

integration_modules:
  - Core
  - EvoAGI
  - Evo_Chaos
  - Evo_EcoSystem
  - EvoNexusBridge
