name: CI

on:
  push:
    branches: ["main", "work", "feat/**", "fix/**", "chore/**", "docs/**", "refactor/**"]
  pull_request:
    branches: ["main", "work"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Lint
        run: |
          ruff check .

      - name: Run smoke tests
        run: |
          python -m compileall .

      - name: Run unit tests
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -q || (echo "::warning ::pytest reported failures"; exit 1)

      - name: EvoAbsolute adapter probe
        run: |
          python -m roles.evo_absolute.lab.visual_env_adapter ci
