name: EvoCodex Ruleset Sync

on:
  workflow_dispatch:
  push:
    branches:
      - codex-review

jobs:
  sync_ruleset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      administration: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
      - name: Apply Evo RulesProto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python EvoBridge/evo_codex_internal.py --apply-ruleset .github/rulesets/EvoRulesProto.yaml
