name: EvoCodex Governance Proto
description: >-
  Proto ruleset ensuring Codex-mediated review and status enforcement for core branches.
target: branch
enforcement: active
conditions:
  ref_name:
    include:
      - refs/heads/main
      - refs/heads/codex-review
    exclude: []
rules:
  - type: pull_request
    parameters:
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: false
      require_last_push_approval: true
      required_approving_review_count: 1
  - type: required_status_checks
    parameters:
      required_status_checks:
        - context: ci/codex
          integration_id: null
      strict_required_status_checks_policy: true
bypass_actors: []
